# Site settings
title: BIMpogovori
email: matevz@bimpogovori.si
description: "Podcast v katerem se Matevž in Robert z gosti sproščeno pogovarjata o informacijskem modeliranju zgradb (BIM) in informacijsko-komunikacijskih tehnologijah</strong> v gradbeništvu."
lang: sl
author: Matevž Dolenc
baseurl: ""
url: "http://bimpogovori.si"
paginate: 5
paginate_path: "/a/page:num"
feed: "http://feeds.feedburner.com/bimpogovori"
image: "http://bimpogovori.si/images/itunes.png"
keywords: informacijsko,modeliranje,zgradb,informacijski,model,bim,komunikacijske,tehnologije 

# Build settings
markdown: kramdown
permalink: /oddaja/:title

gems: [jekyll-paginate]